name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/TestRunner -B ${{runner.workspace}}/build

    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
